apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: 822626594509.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mysql-service.mysql.svc.cluster.local"
        - name: DB_NAME
          value: "employees"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: BACKGROUND_COLOR
          value: "blue"
      imagePullSecrets:
      - name: ecr-secret
