apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: 822626594509.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
    ports:
    - containerPort: 8080
    env:
    - name: DB_HOST
      value: "mysql-service.mysql.svc.cluster.local"
    - name: DB_NAME
      value: "employees"
    - name: DB_USER
      value: "root"
    - name: DB_PASSWORD
      value: "password"
    - name: BACKGROUND_COLOR
      value: "blue"
  imagePullSecrets:
  - name: ecr-secret
